Repository team-B-free/03-GameDuo, pull requests merged in 2022-07, with the labels that each got.

#6 Feat/2
  src/controllers/user/user-controller.js
  src/routes/user/user-router.js
  src/services/user/user-service.js
Labels: ✨ 기능

#7 [Feat] #1 - 보스레이드 시작 구현
  .gitignore
  src/controllers/bossraid-record/bossraid-record-controller.js
  src/controllers/bossraid/bossraid-controller.js
  src/routes/bossraid-record/bossraid-record-router.js
  src/routes/bossraid/bossraid-router.js
  src/routes/index.js
  src/services/bossraid/bossraid-service.js
  src/validations/bossraid/bossraid-validator.js
Labels: ✨ 기능

#10 [Feat] #9 - 보스레이드 시작 기능 수정, jest 추가
  package-lock.json
  package.json
  src/services/bossraid/bossraid-service.js
  src/test/exam/exam-test.js
  src/test/exam/exam.test.js
Labels: ✨ 기능

#11 [Feat] #4 - 보스레이드 상태 조회 기능 구현
  src/controllers/bossraid/bossraid-controller.js
  src/modules/enter-check.js
  src/routes/bossraid/bossraid-router.js
  src/routes/index.js
  src/services/bossraid/bossraid-service.js
Labels: ✨ 기능

#13 [Feat] #5 - 유저 조회 구현
  README.md
  package-lock.json
  package.json
  src/controllers/user/user-controller.js
  src/models/bossraid.js
  src/routes/user/user-router.js
  src/services/bossraid/bossraid-service.js
  src/services/user/user-service.js
  src/validations/exam/exam-validator.js
  src/validations/user/user-validator.js
Labels: ✨ 기능

#14 [Feat] #9 - 보스레이드 시작 기능 변경
  src/controllers/bossraid/bossraid-controller.js
  src/models/bossraid-record.js
  src/routes/bossraid/bossraid-router.js
  src/services/bossraid/bossraid-service.js
  src/validations/bossraid/bossraid-validator.js
Labels: ✨ 기능

#16 Feat/3
  package-lock.json
  package.json
  src/config/redis.js
  src/controllers/bossraid/bossraid-controller.js
  src/modules/static-data.js
  src/modules/time.js
  src/routes/bossraid/bossraid-router.js
  src/services/bossraid/bossraid-service.js
  src/utils/constants.js
  src/utils/response-message.js
  src/validations/bossraid/bossraid-validator.js
Labels: ✨ 기능

#20 Feat/19
  src/controllers/bossraid/bossraid-controller.js
  src/modules/ranking-data.js
  src/routes/bossraid/bossraid-router.js
  src/services/bossraid/bossraid-service.js
  src/utils/constants.js
  src/validations/bossraid/bossraid-validator.js
Labels: ✨ 기능

#22 [Feat] #17 - 레이드 입장시간과 데드라인시간 포맷을 현재 시간(KST)으로 변경
  src/modules/time.js
Labels: ✨ 기능

#24 [Feat] #21 - 보스레이드 종료 시 랭킹 캐싱처리 추가
  src/services/bossraid/bossraid-service.js
Labels: ✨ 기능

#27 [Chore] #26 - 테스트 코드 작성을 위한 환경 설정
  babel.config.json
  jest.config.json
  package-lock.json
  package.json
  src/test/exam/exam.test.js
  src/test/exam/test-modules.js
  src/test/modules/enter-check.test.js
Labels: ⚙ 세팅

#28 [Fix] #25 - 보스레이드 종료 예외처리 추가
  src/services/bossraid/bossraid-service.js
  src/utils/response-message.js
Labels: 🐞 버그 수정

#33 Refactor/32 - 유저 생성 시 반환 데이터값 추가(userId), DB_DATABASE (env값) 적용 코드 수정
  src/controllers/bossraid/bossraid-controller.js
  src/models/index.js
  src/services/user/user-service.js
  src/test/exam/exam.test.js
Labels: ♻️ 리팩토링
